# Generated by Django 3.2 on 2022-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
