# Generated by Django 3.2 on 2022-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0005_letter_has_unseen_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
